In [25]:
from rdkit.Chem.rdmolfiles import MolToSmiles, MolFromSmiles
from rdkit import Chem
import pandas as pd
import re
from collections import defaultdict
import json

In [26]:
db_app = pd.read_csv('drugbank_approved.csv', sep=',')
db_inv = pd.read_csv('drugbank_investigational.csv', sep=',')

In [27]:
db_app

,DrugBank ID,Name,CAS Number,Drug Groups,InChIKey,InChI,SMILES,Formula,KEGG Compound ID,KEGG Drug ID,PubChem Compound ID,PubChem Substance ID,ChEBI ID,ChEMBL ID,HET ID,ChemSpider ID,BindingDB ID
0,DB00006,Bivalirudin,128270-60-0,approved; investigational,OIRCOABEOLEUMC-GEJPAHFPSA-N,InChI=1S/C98H138N24O33/c1-5-52(4)82(96(153)122...,CC[C@H](C)[C@H](NC(=O)[C@H](CCC(O)=O)NC(=O)[C@...,C98H138N24O33,NaN,D03136,16129704.0,46507415.0,59173.0,CHEMBL2103749,NaN,10482069.0,50248103.0
1,DB00014,Goserelin,65807-02-5,approved,BLCLNMBMMGCOAS-URPVMXJPSA-N,InChI=1S/C59H84N18O14/c1-31(2)22-40(49(82)68-3...,CC(C)C[C@H](NC(=O)[C@@H](COC(C)(C)C)NC(=O)[C@H...,C59H84N18O14,NaN,D00573,5311128.0,46507336.0,5523.0,CHEMBL1201247,NaN,4470656.0,NaN
2,DB00027,Gramicidin D,1405-97-6,approved,NDAYQJDHGXTBJL-MWWSRJDJSA-N,InChI=1S/C96H135N19O16/c1-50(2)36-71(105-79(11...,CC(C)C[C@@H](NC(=O)CNC(=O)[C@@H](NC=O)C(C)C)C(...,C96H135N19O16,NaN,D04369,45267103.0,46507412.0,NaN,CHEMBL557217,NaN,24623445.0,NaN
3,DB00035,Desmopressin,16679-58-6,approved,NFLWUMRGJYTJIN-PNIOQBSNSA-N,InChI=1S/C46H64N14O12S2/c47-35(62)15-14-29-40(...,NC(=O)CC[C@@H]1NC(=O)[C@H](CC2=CC=CC=C2)NC(=O)...,C46H64N14O12S2,C06944,D00291,NaN,NaN,4450.0,CHEMBL1429,NaN,4470602.0,50205308.0
4,DB00050,Cetrorelix,120287-85-6,approved; investigational,SBNPWPIBESPSIF-MHWMIDJBSA-N,InChI=1S/C70H92ClN17O14/c1-39(2)31-52(61(94)82...,CC(C)C[C@H](NC(=O)[C@@H](CCCNC(N)=O)NC(=O)[C@H...,C70H92ClN17O14,NaN,D07665,25074887.0,46505494.0,59224.0,CHEMBL1200490,NaN,10482082.0,50369965.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2797,DB19375,Chlorothymol,89-68-9,approved,KFZXVMNBUMVKLN-UHFFFAOYSA-N,InChI=1S/C10H13ClO/c1-6(2)8-5-9(11)7(3)4-10(8)...,CC(C)C1=CC(Cl)=C(C)C=C1O,C10H13ClO,NaN,NaN,NaN,NaN,NaN,CHEMBL1441646,NaN,NaN,NaN
2798,DB19376,Salicylanilide,87-17-2,approved; withdrawn,WKEDVNSFRWHDNR-UHFFFAOYSA-N,InChI=1S/C13H11NO2/c15-12-9-5-4-8-11(12)13(16)...,OC1=CC=CC=C1C(=O)NC1=CC=CC=C1,C13H11NO2,C18915,NaN,NaN,NaN,239133.0,CHEMBL82970,SLI,NaN,234300.0
2799,DB19378,Megestrol,3562-63-8,approved,VXIMPSPISRVBPZ-NWUMPJBXSA-N,InChI=1S/C22H30O3/c1-13-11-16-17(20(3)8-5-15(2...,[H][C@@]12CC[C@](O)(C(C)=O)[C@@]1(C)CC[C@@]1([...,C22H30O3,C07120,NaN,NaN,NaN,6722.0,CHEMBL4071215,NaN,NaN,NaN
2800,DB19379,Syrosingopine,84-36-6,approved; withdrawn,ZCDNRPPFBQDQHR-SSYATKPKSA-N,InChI=1S/C35H42N2O11/c1-7-46-35(40)48-31-26(42...,[H][C@]12C[C@@H](OC(=O)C3=CC(OC)=C(OC(=O)OCC)C...,C35H42N2O11,NaN,NaN,NaN,NaN,32175.0,CHEMBL1399124,NaN,NaN,NaN
2801,DB19387,Acetomenaphthone,573-20-6,approved,RYWSYCQQUDFMAU-UHFFFAOYSA-N,InChI=1S/C15H14O4/c1-9-8-14(18-10(2)16)12-6-4-...,CC(=O)OC1=CC(C)=C(OC(C)=O)C2=CC=CC=C12,C15H14O4,NaN,NaN,NaN,NaN,31164.0,CHEMBL1479848,NaN,NaN,NaN

In [28]:
db_inv

,DrugBank ID,Name,CAS Number,Drug Groups,InChIKey,InChI,SMILES,Formula,KEGG Compound ID,KEGG Drug ID,PubChem Compound ID,PubChem Substance ID,ChEBI ID,ChEMBL ID,HET ID,ChemSpider ID,BindingDB ID
0,DB00006,Bivalirudin,128270-60-0,approved; investigational,OIRCOABEOLEUMC-GEJPAHFPSA-N,InChI=1S/C98H138N24O33/c1-5-52(4)82(96(153)122...,CC[C@H](C)[C@H](NC(=O)[C@H](CCC(O)=O)NC(=O)[C@...,C98H138N24O33,NaN,D03136,16129704.0,46507415.0,59173.0,CHEMBL2103749,NaN,10482069.0,50248103.0
1,DB00050,Cetrorelix,120287-85-6,approved; investigational,SBNPWPIBESPSIF-MHWMIDJBSA-N,InChI=1S/C70H92ClN17O14/c1-39(2)31-52(61(94)82...,CC(C)C[C@H](NC(=O)[C@@H](CCCNC(N)=O)NC(=O)[C@H...,C70H92ClN17O14,NaN,D07665,25074887.0,46505494.0,59224.0,CHEMBL1200490,NaN,10482082.0,50369965.0
2,DB00080,Daptomycin,103060-53-3,approved; investigational,DOAKLVKFURWEDJ-QCMAZARJSA-N,InChI=1S/C72H101N17O26/c1-5-6-7-8-9-10-11-22-5...,CCCCCCCCCC(=O)N[C@@H](CC1=CNC2=C1C=CC=C2)C(=O)...,C72H101N17O26,C12013,D01080,16134395.0,46504551.0,600103.0,CHEMBL4744444,NaN,10200644.0,NaN
3,DB00091,Cyclosporine,59865-13-3,approved; investigational; vet_approved,PMATZTZNYRCHOR-CGLBZJNRSA-N,InChI=1S/C62H111N11O12/c1-25-27-28-40(15)52(75...,CC[C@@H]1NC(=O)[C@H]([C@H](O)[C@H](C)C\C=C\C)N...,C62H111N11O12,C05086,D00184,5284373.0,46508198.0,4031.0,CHEMBL160,NaN,4447449.0,50022815.0
4,DB00106,Abarelix,183552-38-7,approved; investigational; withdrawn,AIWRTTMUVOZGPW-HSPKUQOVSA-N,InChI=1S/C72H95ClN14O14/c1-41(2)32-54(64(93)80...,CC(C)C[C@H](NC(=O)[C@@H](CC(N)=O)NC(=O)[C@H](C...,C72H95ClN14O14,NaN,D02738,16131215.0,46508237.0,337298.0,CHEMBL1252,NaN,10482301.0,50102442.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5296,DB19450,TDI-01,NaN,investigational,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5297,DB19451,Ibuzatrelvir,2755812-39-4,investigational,WGNWEPPRWQKSKI-AIEDFZFUSA-N,"InChI=1S/C21H30F3N5O5/c1-20(2,3)15(28-19(33)34...",COC(=O)N[C@H](C(=O)N1C[C@@H](C[C@H]1C(=O)N[C@@...,C21H30F3N5O5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5298,DB19454,Cetyl oleate,22393-86-8,investigational,JYTMDBGMUIAIQH-ZPHPHTNESA-N,InChI=1S/C34H66O2/c1-3-5-7-9-11-13-15-17-19-20...,CCCCCCCCCCCCCCCCOC(=O)CCCCCCC\C=C/CCCCCCCC,C34H66O2,NaN,NaN,NaN,NaN,75622.0,NaN,NaN,NaN,NaN
5299,DB19455,Cetyl myristoleate,64660-84-0,investigational,DYIOQMKBBPSAFY-BENRWUELSA-N,InChI=1S/C30H58O2/c1-3-5-7-9-11-13-15-16-17-19...,CCCCCCCCCCCCCCCCOC(=O)CCCCCCC\C=C/CCCC,C30H58O2,NaN,NaN,NaN,NaN,165719.0,NaN,NaN,NaN,NaN
5300,DB19456,Cetyl palmitoleate,22393-83-5,investigational,YEHRXIRYXGNEDS-PEZBUJJGSA-N,InChI=1S/C32H62O2/c1-3-5-7-9-11-13-15-17-19-21...,CCCCCCCCCCCCCCCCOC(=O)CCCCCCC\C=C/CCCCCC,C32H62O2,NaN,NaN,NaN,NaN,75629.0,NaN,NaN,NaN,NaN

In [29]:
overlapped = []
db_inv_id = db_inv['DrugBank ID'].to_list()
db_app_id = db_app['DrugBank ID'].to_list()
for id in db_inv_id:
    if id in db_app_id:
        db_inv_id.remove(id)
print('Number of unique investigational drugs:', len(db_inv_id))

Number of unique investigational drugs: 4535

In [30]:
unique_inv = db_inv[db_inv['DrugBank ID'].isin(db_inv_id)]

In [31]:
df_db = pd.concat([db_app,unique_inv],axis=0)

In [32]:
db_smiles = list(set(df_db['SMILES'].to_list()))
print('Number of smiles:', len(db_smiles))

Number of smiles: 6116

In [33]:
print(db_smiles)

['[H][C@]12CC[C@](C)(C1(C)C)[C@@](C2)(OCCN(C)C)C1=CC=CC=C1', 'COC1=C(OC(=O)N2CCN(C)C[C@H]2C)C=C2C(NC3=C(F)C(Cl)=CC=C3)=NC=NC2=C1', 'FC1=C(F)C=C(CN2CCC(CC2)NC2=CC=C(N=N2)C(F)(F)F)C=C1', 'COCCC[C@H](NC(=O)[C@@H]1CCCN1C(=O)[C@@H](CC1=CC=CC=C1)NC(=O)OCC1=CC=CC=C1)B(O)O', 'CC1=CC(=O)N(O)C(=C1)C1CCCCC1', 'ClC1=CC=C(OS(=O)(=O)C2=CC=C(Cl)C=C2)C=C1', '[H][C@@]1(C[C@@](O)(CC2=C(O)C3=C(C(O)=C12)C(=O)C1=C(C=CC=C1OC)C3=O)C(=O)CO)O[C@H]1C[C@H](N)[C@H](OCC2=CC=CC=C2)[C@H](C)O1', '[H][C@@]12CCC3=CC(=CC=C3[C@@]1(CCN2C(=O)[C@@H]1CC[C@H](C[C@@H]1C)C(O)=O)S(=O)(=O)C1=CC=C(F)C=C1)C(F)(C(F)(F)F)C(F)(F)F', 'O=C1COC(=O)CO1', 'CC(C)CCC[C@@H](C)CCC[C@@H](C)CCC[C@]1(C)CCC2=C(C)C(OC(C)=O)=C(C)C(C)=C2O1', 'COC1=C(OC)C=C(CCO[C@@H]2CCCC[C@H]2N2CC[C@@H](O)C2)C=C1', 'CCCCC(CC)COC(=O)CC(C(=O)OCC(CC)CCCC)S(O)(=O)=O', 'OC(=O)CNC(=O)C1=C(O)C2=CC=CC=C2N(OCC2CC2)C1=O', '[H]C(=O)[C@H](NC(C)=O)[C@@H](O)[C@H](O)[C@H](O)CO', '[Zn++].[O-]S([O-])(=O)=O', 'C[C@H](N)C(=O)N[C@@H](C)C(=O)OCCOC1=CC=C(C=C1)C1=C(C#N)C(=NC(SCC2=CSC(=N2)C2=CC=C(Cl)C=C2)=C1C#N)N1CCCC1', '[H][C@@]12C[C@@H](C)[C@](O)(C(=O)COC(C)=O)[C@@]1(C)C[C@H](O)[C@@]1(F)[C@@]2([H])CCC2=CC(=O)C=C[C@]12C', 'C\\C=C1/NC(=O)[C@H]2CSSCC\\C=C\\[C@H](CC(=O)N[C@H](C(C)C)C(=O)N2)OC(=O)[C@@H](NC1=O)C(C)C', 'COC1=CC(N[C@H](C(=O)C2=CNC3=CC=C(OC(F)(F)F)C=C23)C2=CC=C(Cl)C=C2OC)=CC(=C1)S(C)(=O)=O', '[H][C@@]12CCCN1C(=O)[C@H](CC(C)C)N1C(=O)[C@](NC(=O)[C@H]3CN(C)[C@]4([H])CC5=CNC6=CC=CC(=C56)[C@@]4([H])C3)(O[C@@]21O)C(C)C', 'COC1=CC(O)=C(C=C1)C(=O)C1=CC=CC=C1', 'COC1=CC(\\C=C\\C(=O)CC(=O)\\C=C\\C2=CC(OC)=C(O)C=C2)=CC=C1O', 'CCCN(CCC)S(=O)(=O)C1=CC=C(C=C1)C(O)=O', 'C[C@H]([C@H](C(=O)NC1=C(Cl)C=CC(=C1)[C@@H](CC(O)=O)C1CC1)C1=CC=C(Cl)C=C1)C(F)(F)F', 'CN1C(CCCC(O)=O)=NC2=CC(=CC=C12)N(CCCl)CCCl', '[Fe+3].[Fe+3].[Fe+3].[Fe+3].N#C[Fe-4](C#N)(C#N)(C#N)(C#N)C#N.N#C[Fe-4](C#N)(C#N)(C#N)(C#N)C#N.N#C[Fe-4](C#N)(C#N)(C#N)(C#N)C#N', '[Na+].[Na+].[Na+].[Na+].CC1=C(OP([O-])([O-])=O)C2=CC=CC=C2C(OP([O-])([O-])=O)=C1', 'COC1=C(OCCCN2CCOCC2)C=CC2=C1N=C(NC(=O)C1=CN=C(N)N=C1)N1CCN=C21', '[H][C@@]1(CC[C@@]2([H])[C@]3([H])[C@@H](O)C[C@]4([H])C[C@H](O)CC[C@]4(C)[C@@]3([H])CC[C@]12C)[C@H](C)CCC(=O)OC1=CC=C(\\C=C\\C(=O)OCCCCO[N+]([O-])=O)C=C1OC', '[H]\\C(COCC)=C(\\[H])C1=CC=C(C=C1)C1=NC(=C(N1)C1=CC=C(NC(C)C)C=C1)C1=CC=C(NC(C)C)C=C1', '[2H]C([2H])(\\C=C/CCCCC)\\C=C/CCCCCCCC(=O)OCC', 'C[C@H]1C[C@H]2CSC(N)=N[C@]2(CO1)C1=NC(NC(=O)C2=NC=C(OC(F)F)C=C2)=CS1', 'OP(O)(=O)OCN1C(=O)NC(C1=O)(C1=CC=CC=C1)C1=CC=CC=C1', 'CC(C)=CCOC1=C(Cl)C=CC(NC(=S)C2=C(C)OC=C2)=C1', 'CC(C)[C@@H]1NC(=O)[C@H](CC2=CC=CC=C2)NC(=O)[C@@H]2NC(=O)[C@H](CC3=CC=CC=C3)NC(=O)[C@@H]3CCCN3C(=O)CNC(=O)[C@H](CC3=CC=CC=C3)NC(=O)[C@@H]3CNCCCC[C@H](NC(=O)[C@@H]4NC(=O)[C@H](CC(N)=O)NC(=O)CNC(=O)[C@@H](NC(=O)[C@H](CSC[C@@H](NC(=O)[C@H](CCC(N)=O)NC(=O)[C@H](CCCCN)NC(=O)[C@@H](N)CS[C@H]4C)C(=O)N[C@@H](CS[C@H]2C)C(=O)N3)NC1=O)[C@@H](O)C(O)=O)C(O)=O', '[H][C@@]12CC[C@](O)(C(=O)CS)[C@@]1(C)C[C@H](O)[C@@]1([H])[C@@]2([H])CCC2=CC(=O)CC[C@]12C', 'OC1(CCN(CCCC(=O)C2=CC=C(F)C=C2)CC1)C1=CC=C(Cl)C=C1', '[OH-].[OH-].[OH-].[OH-].[Al+3].[Al+3].[Cl-].NC(=O)NC1NC(=O)[N-]C1=O', '[H]O[Cl](=O)=O', 'NC1=NC(=O)N(C=C1)[C@H]1CO[C@@H](CO)S1', 'ONC(=O)CCCCCCNC(=O)C1=CN=C(N=C1)N(C1=CC=CC=C1)C1=CC=CC=C1Cl', '[H][C@]12CC[C@]([H])(C[C@@]([H])(C1)OC(C1=CC=CC=C1)C1=CC=CC=C1)N2C', 'FC(F)(F)C1=CC=C(COC(CN2C=CN=C2)C2=CC=C(Cl)C=C2Cl)C=C1', '[Cs]', 'CN1C2=N[C@@H]3CCC[C@@H]3N2C2=NN(CC3=CC=C(C=C3)C3=NC(F)=CC=C3)C(NC3=CC=CC=C3)=C2C1=O', '[H][C@]12SCC(CSC3=NN=NN3C)=C(N1C(=O)[C@]2(NC(=O)CSCC#N)OC)C(O)=O', 'O=C=O', 'COC(=O)C1=C(C=CC=C1)C1=C2C=CC(=N)C(Br)=C2OC2=C1C=CC(N)=C2Br', 'OC(=O)CCCCC(O)=O.C[C@@H](N)COC1=CC=C(C=C1)C1=CN=C2C=CC(N[C@H](C)C3=CC=CC(F)=C3)=NN12', 'CCCC1=CC(O)=C2[C@@H]3C=C(C)CC[C@H]3C(C)(C)OC2=C1', 'CCC1=C(C)C=C(C(=O)NC2(CCCCC2)C(O)=O)C(=O)N1CC1=CC=C(F)C=C1', '[Na+].[H][C@]12CC[C@@](CS([O-])(=O)=O)(C(=O)C1)C2(C)C', '[Cl-].COC(C[197Hg+])CNC(N)=O', 'CC1=NC(C(=O)NCC(O)=O)=C(O)C2=C1C=C(OC1=CC=CC=C1)C=C2', 'CC(C)[C@@H](NC(=O)NCC(C)(C)O)C(=O)N1CC[C@](O)(C2=CC=C(Cl)C=C2)C(C)(C)C1', 'CN(C)CCC(C1=CC=C(Cl)C=C1)C1=CC=CC=N1', 'OC(=O)CN(CC(O)=O)CC1=CC2=C(OC3=CC(O)=C(CN(CC(O)=O)CC(O)=O)C=C3C22OC(=O)C3=CC=CC=C23)C=C1O', 'CC1=NN(C=C1CN1CCC2(CC1)OCC(F)(F)C1=C2SC(Cl)=C1)C1=NC=CC=C1CO', '[H][C@@]1(CC[C@@]2([H])[C@]3([H])[C@@H](O)C=C4C[C@H](CC[C@]4(C)[C@@]3([H])CC[C@]12C)OC(=O)CCCCCCC\\C=C/CCCCCCCC)[C@H](C)CCCC(C)C', 'OC[C@@H](O)[C@@H](O)[C@H](O)[C@@H](F)C=O', 'COC1=C(Cl)C2=NC(=CC(O[C@@H]3C[C@@H]4N(C3)C(=O)[C@H](CCCCCCC[C@@H]3C[C@]3(NC4=O)P(O)(=O)CC3=C(F)C=CC=C3F)NC(=O)OC3CCCC3)=C2C=C1)C1=CSC(NC(C)C)=N1', '[H][C@@]12C(=O)CC[C@]11CCC(C)[C@@]2(C)[C@@H](C[C@@](C)(C=C)[C@@H](O)[C@@H]1C)OC(=O)CS[C@@H]1CC[C@@H](N)C[C@H]1O', 'COC1=CC=C2NC=C(CCNC(=O)C3=CC(=O)C=CO3)C2=C1', 'NC(=O)C1=CC=CC(=C1)[C@@H]1C[C@@H]2CC[C@H](C1)N2CCN(CC1CCCCC1)C(=O)[C@@H](O)CO', 'CC(CN1CCCCC1)CC1=CC=C(C=C1)C(C)(C)C', 'FC1=CC=C(C=C1)C(CCCN1CCC(CC1)N1C(=O)NC2=CC=CC=C12)C1=CC=C(F)C=C1', 'COC(=O)NC1=C(N)N=C(N=C1N)C1=NN(CC2=CC=CC=C2F)C2=C1C=C(F)C=N2', 'COC(=O)N1CCC(CN2CCC(CNC(=O)C3=C4NC(=NC4=CC=C3)C(C)C)CC2)CC1', 'NS(=O)(=O)C1=CC(=C(Cl)C(Cl)=C1)S(N)(=O)=O', 'CN1C=C(C=N1)C1=CC2=C(C=C1)N(C=N2)C1=CC(=CC(NS(=O)(=O)C2CC2)=C1)C1=C(F)C=C(F)C=C1', 'C\\C(\\C=C\\C=C(/C)\\C=C\\C(O)=O)=C/C=C/C=C(\\C)/C=C/C=C(\\C)/C=C/C(O)=O', 'COC[C@@H](N1CCN(C)CC1)C(=O)NC1=C2NC=C(C2=CC=C1)C1=NC(NC2=CC=CC(=C2F)S(C)(=O)=O)=NC=C1F', 'CC1=C2N3C=NN=C3SC2=CC=C1', '[H][C@@]1(CC2=CC=CN=C2)N2CCC(CC2)[C@@]1([H])NC(=O)C1=CC2=C(O1)C=CC=C2', 'CCOC(=O)C1=CC=C(N)C=C1', 'Cl.CCN(C\\C=C/C1=CC(Cl)=C(C=C1)C1CCCCC1)C1CCCCC1', 'CN(C)CCN(C)C1=NC(OCC(F)(F)F)=C(NC2=NC=CC(=N2)C2=CN(C)C3=C2C=CC=C3)C=C1NC(=O)C=C', 'O=[Zn]', 'CC(C)[C@H](O)C(=O)N[C@@H](C)C(=O)N[C@H]1C2=CC=CC=C2CCN(C)C1=O', 'CCN(CC)CCNC(=O)C1=CC(Br)=C(N)C=C1OC', 'C1CN(CCO1)C1=CC=C(NC2=NC(=CN3C=CN=C23)C2=CC3=C(C=NN3)C=C2)C=C1', 'C[C@@]1(O)C[C@@H](C1)C1=NC(=C2N1C=CN=C2N)C1=CC=C2C=CC(=NC2=C1)C1=CC=CC=C1', 'C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@H]34)[C@@H]1CC[C@@H]2OS(O)(=O)=O', 'CN(C1CCN(CC1)C1=NC2=C(C=CC=C2)N1CC1=CC=C(F)C=C1)C1=NC=CC(=O)N1', 'CC(C(O)=O)C1=CC=CC2=C1OC=C2C1=CC=CC=C1', '[Cl-].CCC(=O)OCCNC(=O)C[N+]1=CC=CC=C1', 'CC1=CC=C(C=C1)S(N)(=O)=O', 'NC(=N)C1=CC=C(C=C1)C1=CC=C(OC[C@@H]2C[C@@H](CC(O)=O)C(=O)N2)C=C1', 'NC1=NC(N)=C2N=CN([C@H]3CO[C@@H](CO)O3)C2=N1', 'CN1C=C(C=N1)C1=CC2=C(C=C1)C=NC(NC(=O)C1=CC=NC(=C1)N1CCN(C)CC1)=C2', 'NC(=N)C1=CC=C(OCCCOC2=CC=C(C=C2)C(N)=N)C=C1', 'CCC(CC)CC1(CCCCC1)C(=O)NC1=CC=CC=C1SC(=O)C(C)C', '[H]N[C@@H](CCCCN)C(=O)N[C@H]1CSSC[C@H](NC(=O)[C@@]([H])(NC(=O)[C@H](C)NC(=O)[C@@]([H])(NC(=O)[C@H](CC(N)=O)NC1=O)[C@@H](C)O)[C@@H](C)O)C(=O)N[C@@H](C)C(=O)N[C@@]([H])([C@@H](C)O)C(=O)N[C@@H](CCC(N)=O)C(=O)N[C@@H](CCCNC(N)=N)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](C)C(=O)N[C@@H](CC(N)=O)C(=O)N[C@@H](CC1=CC=CC=C1)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](C(C)C)C(=O)N[C@@H](CC1=CN=CN1)C(=O)N[C@@H](CO)C(=O)N[C@@H](CO)C(=O)N[C@@H](CC(N)=O)C(=O)N[C@@H](CC(N)=O)C(=O)N[C@@H](CC1=CC=CC=C1)C(=O)NCC(=O)N1CCC[C@H]1C(=O)N[C@@]([H])([C@@H](C)CC)C(=O)N[C@@H](CC(C)C)C(=O)N1CCC[C@H]1C(=O)N1CCC[C@H]1C(=O)N[C@@]([H])([C@@H](C)O)C(=O)N[C@@H](CC(N)=O)C(=O)N[C@@H](C(C)C)C(=O)NCC(=O)N[C@@H](CO)C(=O)N[C@@H](CC(N)=O)C(=O)N[C@@]([H])([C@@H](C)O)C(=O)N[C@@H](CC1=CC=C(O)C=C1)C(N)=O', 'CNC(=N)NCCC[C@H](N)C(O)=O', 'CC(C)(C)NC[C@H](O)C1=CC(CO)=C(O)C=C1', 'CC1=CC(F)=CC=C1C1=CC=C(C=N1)\\N=N\\C1=C(N)C2=CC=CC=C2C(=C1)S(O)(=O)=O', '[Mg++].CC([O-])=O.CC([O-])=O', '[H][C@@]1([C@H](O)[C@H](C)CCCCCCNC(C)=O)N(C)C(=O)[C@H](C(C)C)N(C)C(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H](C)NC(=O)[C@H](C)NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H](NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H](C)N(C)C(=O)[C@H](CC)NC1=O)C(C)C', 'CCCCCCOC(=O)C1=CC=CC=C1C(=O)C1=CC=C(C=C1O)N(CC)CC', '[NH4+].CC(O)C([O-])=O', 'CC(C)(C)CC(C)(C)C1=CC(CC2=C(O)C(=CC(=C2)C(C)(C)CC(C)(C)C)N2N=C3C=CC=CC3=N2)=C(O)C(=C1)N1N=C2C=CC=CC2=N1', 'CN1CC[C@@H]([C@H](O)C1)C1=C(O)C=C(O)C2=C1OC(=CC2=O)C1=CC=CC=C1Cl', '[H][C@]12C[C@@]3([H])[C@]4([H])CC[C@]5([H])C[C@@H](O)CC[C@]5(C)[C@@]4([H])CC[C@]3(C)[C@@]1([H])[C@H](C)[C@@]1(CC[C@@H](C)CO1)O2', '[H][C@@]12CC[C@](O)(C(=O)COC(C)=O)[C@@]1(C)C[C@H](O)[C@@]1([H])[C@@]2([H])CCC2=CC(=O)CC[C@]12C', 'CCC1=CC(=CC(C)=C1OC[C@@H](O)CO)C1=NOC(=N1)C1=CC(=NC(OC)=C1)C1CCCC1', 'CO[C@@H]1CCN(C[C@@H]1F)C1=NC=CC(NC2=CC3=C(C=CC(N4C[C@H](CS(C)(=O)=O)[C@H]4C)=C3C=N2)C(C)C)=N1', 'C[N+](C)(C)CCO.CN1C2=C([N-]C=N2)C(=O)N(C)C1=O', 'COC1=CC2=C(NC(=N2)[S@@](=O)CC2=NC=C(C)C(OC)=C2C)C=C1', 'CC#CC(=O)N[C@H]1CCCN(C1)C1=C2C(C)=C(C)NC2=C(C=C1F)C(N)=O', '[H][C@]12SCC(COC(N)=O)=C(N1C(=O)[C@H]2NC(=O)C(=N/OC)\\C1=CC=CO1)C(O)=O', 'C\\C1=C/CC[C@@]2(C)O[C@H]2[C@H]2OC(=O)C(=C)[C@@H]2CC1', 'CNC(=O)C1=CC=C(C)C(=C1)N1C(C)=CC(OCC2=C(F)C=C(F)C=C2)=C(Br)C1=O', 'COC1=CC2=C(C=C1OC)C(OC1=CC=C(NC(=O)C3(CC3)C(=O)NC3=CC=C(F)C=C3)C=C1)=CC=N2', 'CNC(=O)C1=CC(OC2=CC(F)=C(NC(=O)NC3=CC=C(Cl)C(=C3)C(F)(F)F)C=C2)=CC=N1', 'CCC(C)C(CC)C(N)=O', '[H][C@]12SCC(CSC3=NN=NN3C)=C(N1C(=O)[C@H]2NC(=O)C(=N/OC)\\C1=CSC(N)=N1)C(O)=O', 'NC(=O)CS(=O)C(C1=CC=CC=C1)C1=CC=CC=C1', '[H][C@]1(C\\C=C(C)/CCC[C@H](C)[C@H](O)[C@@H](C)C(=O)C(C)(C)[C@@H](O)CC(=O)O1)C(\\C)=C\\C1=CSC(C)=N1', '[H][C@@]1([C@H](OC)[C@@H](CC[C@]11CO1)OC(=O)N[C@H](C(C)C)C(N)=O)[C@@]1(C)O[C@@H]1CC=C(C)C', 'CC(C)C1=C(CCC2=NOC3=CC(OCC(O)=O)=C(C)C=C23)SC(=N1)C1=CC=C(C=C1)C(F)(F)F', 'NC1=C2N=CN(CCOCP(O)(O)=O)C2=NC=N1', 'OC(=O)CNC(=O)C1=CC=CC=C1I', 'C[C@@H](O)C1=NN=C(O1)[C@H]1C[C@@H](C1)NC(=O)C1=CC(=NO1)C1=CC=CC=C1', '[Ca++].[O-]C([O-])=O', 'CN1N=CN=C1[C@@H]1[C@H](NC2=C3C1=NNC(=O)C3=CC(F)=C2)C1=CC=C(F)C=C1', '[H][C@@]12N3CC[C@@]11C4=CC(=C(OC)C=C4N(C)[C@@]1([H])[C@](O)([C@H](O)[C@]2(CC)C=CC3)C(=O)NNC(=O)OCCSSC[C@H](NC(=O)[C@H](CC(O)=O)NC(=O)[C@H](CC(O)=O)NC(=O)[C@H](CCCNC(N)=N)NC(=O)[C@H](CC(O)=O)NC(=O)CC[C@H](NC(=O)C1=CC=C(NCC2=CNC3=NC(N)=NC(=O)C3=N2)C=C1)C(O)=O)C(O)=O)[C@]1(C[C@@]2([H])C[N@](C[C@](O)(CC)C2)CCC2=C1NC1=CC=CC=C21)C(=O)OC', 'O=C1CCC2=C(N1)C=CC(OCCCCC1=NN=NN1C1CCCCC1)=C2', 'CCCCOC(=O)C1=CC=C(O)C=C1', 'CC(OC1=C(Cl)C=CC=C1Cl)C1=NCCN1', 'OS(=O)(=O)CCS[C@H]1CCO[P@@](=O)(N1)N(CCCl)CCCl', 'CN(C)CCC1=CNC2=C1C(OP(O)(O)=O)=CC=C2', 'CCCCCCCCCCCCCCCC(=O)OC[C@H](COP([O-])(=O)OCC[N+](C)(C)C)OC(=O)CCCCCCCCCCCCCCC', 'C[C@H]([C@H](N)C1=NC2=CC=C(C=C2N1)C(C)(C)C)C(N)=O', 'CC1=CC(C)=NC(NS(=O)(=O)C2=CC=C(N)C=C2)=N1', 'CN(C)C(=O)C1=CC(NC(=O)[C@H]2CCC(=O)N2C2CCN(CC3=CC=C(Cl)C(C)=C3)CC2)=NC(C)=C1', 'N#CC[C@H](C1CCCC1)N1C=C(C=N1)C1=C2C=CNC2=NC=N1', 'CCCCCCCCCCCCOC(=O)CN(C)C(N)=N', '[H][C@]12C3=CC=CC=C3[C@H](N3CCN(C[C@@H](O)COC4=CC=CC5=C4C=CC=N5)CC3)C3=CC=CC=C3[C@@]1([H])C2(F)F', 'C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@H]34)[C@@H]1C[C@H]1O[C@H](O[C@@]21C(=O)C[18F])C1=CC=CO1', '[Au+].[S-]CC(=O)NC1=CC=CC=C1', 'CC1(COC2=CC=C3N(C=NC3=C2)C2=CC=C3C=CC=C(N4CCC(N)CC4)C3=N2)COC1', 'CN1C(=O)C=C(N2CCC[C@@H](N)C2)N(CC2=CC(F)=CC=C2C#N)C1=O', 'O=C1N(NC=C1N1C=CN=N1)C1=NC=NC(=C1)N1CCOCC1', 'C[N+](C)(C)CCOP([O-])(=O)OCCCCCCCCCCCCCCCCCCC1=CC=C([131I])C=C1', 'ClC1=CC=C(C=C1)C1=C(NC(=O)C2=C(Cl)N=CC=C2)C=CC=C1', 'C[C@H](O)[C@H](C)[C@@H]1O[C@H]1C[C@H]1CO[C@@H](C\\C(C)=C\\C(=O)OCCCCCCCCC(O)=O)[C@H](O)[C@@H]1O', 'COC[C@H](NC(=O)[C@H](COC)NC(=O)C1=CN=C(C)S1)C(=O)N[C@@H](CC1=CC=CC=C1)C(=O)[C@@]1(C)CO1', 'COC1=C(NC2=NC=C(C(=O)OC(C)C)C(=N2)C2=CN(C)C3=C2C=CC=C3)C=C(NC(=O)C=C)C(=C1)N(C)CCN(C)C', 'OC(=O)C1=C(I)C(NC(=O)CCCCC(=O)NC2=C(I)C=C(I)C(C(O)=O)=C2I)=C(I)C=C1I', '[H][C@@]12CN(C)C[C@]1([H])[C@H]2CN(CC1=CC(Cl)=C(F)C=C1)C(=O)C1=CN(C)C=N1', 'CCN1C=C(C(O)=O)C(=O)C2=CC(F)=C(C=C12)N1CCNCC1', 'CN(C)CCCN1C2=CC=CC=C2CCC2=CC=CC=C12', 'CC1=CC(=CC=C1C(=O)NC1CC1)C1=C2N=C(OC3=CC=CN=C3)C=C(NC[C@H]3C[C@@](C)(O)C3)N2N=C1', 'O=C(CS(=O)CC1=CC=CO1)NC\\C=C/COC1=NC=CC(CN2CCCCC2)=C1', 'NC1=CC=C(C=C1)C(=O)NC1=CC=CC=C1N', '[Fe++].[H][C@@](O)(CO)[C@@]([H])(O)[C@]([H])(O)[C@@]([H])(O)C([O-])=O.[H][C@@](O)(CO)[C@@]([H])(O)[C@]([H])(O)[C@@]([H])(O)C([O-])=O', '[O-][N+]1=CC(=CC=C1)C1=NC2=C(Cl)C=CC=C2C=C1[C@@H](NC1=NC=NC2=CC=CN=C12)C(F)(F)F', 'COC1=CC=C(\\C=C\\C)C=C1', '[Zn++].[Zn++].[Zn++].OC(CC([O-])=O)(CC([O-])=O)C([O-])=O.OC(CC([O-])=O)(CC([O-])=O)C([O-])=O', 'C1CN(CCN1C1=NC=CC=N1)C1=C(C=C(N=N1)C1=CC=CC=C1)C1=CC=NC=C1', 'CCCOC1=C(C=C(C=C1)S(=O)(=O)NCCC1CCCN1C)C1=NC(=O)C2=C(N1)C(CCC)=NN2C', '[H][C@@]12C[C@]1([H])N([C@@H](C2)C#N)C(=O)[C@@H](N)C12CC3CC(CC(O)(C3)C1)C2', 'CCCCOP(O)(=O)OC[C@H]1O[C@H](C[C@@H]1OP(O)(=O)OCCCC)N1C=C(C)C(=O)NC1=O', 'CC(C)(C)C1=CN=C(CSC2=CN=C(NC(=O)C3CCNCC3)S2)O1', 'COC(=O)C1=C(C)NC(C)=C(C1C1=CC=CC2=NON=C12)C(=O)OC(C)C', 'CCCCCCO[C@@H](C)C1=C(OC)C(=CC=C1)C1=CSC(NC(=O)C2=CC(Cl)=C(\\C=C(/C)C(O)=O)C(Cl)=C2)=N1', 'CCOC(=O)CC(O)(CC(=O)OCC)C(=O)OCC', 'CC1(C)CC(CC(C)(C)N1O)OC(=O)C1CC1', '[Ca++].CC([O-])=O.CC([O-])=O', 'CC(C)=CCC\\C(C)=C\\CNCCNC1C2CC3CC(C2)CC1C3', 'OC1=C(Cl)C=C(C=C1Cl)C(=O)N1CS(=O)(=O)C2=CC=CC=C12', 'CO[C@H]1C[C@H](C)CC2=C(N)C(=O)C=C(NC(=O)\\C(C)=C\\C=C/[C@H](OC)[C@@H](OC(N)=O)\\C(C)=C\\[C@H](C)[C@H]1O)C2=O', 'NC1=NC(=O)N(C[C@@H](CO)OCP(O)(O)=O)C=C1', 'COC(=O)N[C@@H](C(C)C)C(=O)N1[C@@H](C[C@@H]2CCCC[C@H]12)C1=NC2=CC=C(C=C2N1)C1=CC2=CC=C1CCC1=CC=C(CC2)C(=C1)C1=CC=C2N=C(NC2=C1)[C@@H]1C[C@@H]2CCCC[C@@H]2N1C(=O)[C@@H](NC(=O)OC)C(C)C', 'COCCOC1=CC=C(C=C1)N1CCN(CCN2N=CC3=C2N=C(N)N2N=C(N=C32)C2=CC=CO2)CC1', 'FC(F)(F)C1=CC=C(CNC2=NC=C(CC3=CNC4=NC=C(Cl)C=C34)C=C2)C=N1', 'CC1=C2N=C(C3=CC=CC=C3Cl)C3=C(NC2=NN1)C=C(N=C3)N1CCOCC1', 'O=C1OC2=CC3=C(C=CO3)C=C2C=C1', 'OC1=CC(=CC(O)=C1O)C(=O)OC1=C(O)C(O)=CC(=C1)C(=O)OC[C@H]1OC(OC(=O)C2=CC(OC(=O)C3=CC(O)=C(O)C(O)=C3)=C(O)C(O)=C2)[C@H](OC(=O)C2=CC(OC(=O)C3=CC(O)=C(O)C(O)=C3)=C(O)C(O)=C2)[C@@H](OC(=O)C2=CC(OC(=O)C3=CC(O)=C(O)C(O)=C3)=C(O)C(O)=C2)[C@@H]1OC(=O)C1=CC(OC(=O)C2=CC(O)=C(O)C(O)=C2)=C(O)C(O)=C1', 'O=C1CCCC(=O)N1CCC1=CN=CN1', 'CCCCCCCCN1CCC2=C1C(NC(=O)C(C)(C)C)=C(C)C(CC(O)=O)=C2C', '[H][C@]1(C)C[C@@]2([H])[C@]3([H])CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)C(=O)C[C@]2(C)[C@@]1(O)C(=O)CCl', 'C[N+](C)(C)[C@@H](CC1=CNC(=S)N1)C([O-])=O', 'CCC(O)(CC)\\C=C\\C[C@H](C)C1=CC[C@@]2([H])\\C(CCC[C@]12C)=C\\C=C1\\C[C@@H](O)C[C@@](F)([H])C1=C', 'O[Bi]1OC2=CC(=CC(O)=C2O1)C(O)=O', 'CSCC[C@H](NC=O)C(=O)N[C@@H](CC(O)=O)C(=O)NCC(=O)N[C@@H](CS)C(=O)N[C@@H](CCC(O)=O)C(=O)N[C@@H](CC(C)C)C(O)=O', 'COC1=CC=C(Cl)C=C1[C@]1(F)C(=O)NC2=C1C=CC(=C2)C(F)(F)F', '[H][C@@]12CCC[C@]1([H])CN(C2)NC(=O)NS(=O)(=O)C1=CC=C(C)C=C1', 'FC1=C(N2CCC(=O)C=C2)C(F)=C(F)C(=C1)N1C[C@H](CNC2=NOC=C2)OC1=O', 'CNC1=C(F)C=C2C(NC(=O)N(C2=O)C2=CC=C(NC(=O)NS(=O)(=O)C3=CC=C(Cl)S3)C=C2)=C1', 'CC[C@@H]1SC2(CCN(C)CC2)NC1=O', 'COC1=CC=CC(OCCCN)=C1C1=CC(NC2=CN=C(C=N2)C#N)=NN1', 'CC(=O)NO', 'NC(=N)NCC1COC2=C(O1)C=CC=C2', 'CCC[C@@H](NC(=O)N1[C@@H](OC2=CC=C(C=C2)C(=O)N2CCN(C)CC2)C(CC)(CC)C1=O)C1=CC=C2OCOC2=C1', 'COC(=O)N[C@H](C(=O)N[C@@H](CC1=CC=CC=C1)[C@@H](O)CN(CC1=CC=C(C=C1)C1=CC=CC=N1)NC(=O)[C@@H](NC(=O)OC)C(C)(C)C)C(C)(C)C', 'CCC[C@@H]([C@@H](C1=CNC2=C1C=C(C)C=C2F)C1=CC=C(Cl)C=C1)C1=CC=C(C=C1)C(=O)NCCC(O)=O', 'O[Se](O)=O', 'CC1=NC(C(=O)N2CCCC[C@H]2CNC(=O)C2=CC=CC3=C2C=CO3)=C(S1)C1=CC=C(F)C=C1', 'CCC(=O)C(CCN(C)C)(C1=CC=CC=C1)C1=CC=CC=C1', 'FC(F)(C1=NN=C2C=CC(=NN12)C1=CC=NC=C1)C1=CC2=C(C=C1)N=CC=C2', 'C[C@@H](NC(=O)C1=C(Cl)C(N)=NC=N1)C1=NC=C(S1)C(=O)NC1=NC=C(Cl)C(=C1)C(F)(F)F', 'CC(C)OC(=O)C(C)(C)N[P@@](=O)(CO[C@H](C)CN1C=NC2=C(N)N=CN=C12)OC1=CC=CC=C1', 'OC(=O)C1N=C(C2=CC=CC=C2)C2=C(NC1=O)C=CC(Cl)=C2', 'CCOC1=CC=CC=C1C(=O)NCC1=COC(=N1)C1=CC=C(OC(F)F)C(OC(C)C)=C1', 'CCCN1CCN(CC1)C1=CC=C(C=C1)C(=O)NC1(CCCCC1)C(=O)NCC#N', 'COC1=CC=C(C=C1)C(=O)CC(=O)C1=CC=C(C=C1)C(C)(C)C', 'ClC1=CC(N2CCN(CCCCN3C(=O)C4=C(C=CC=C4)S3(=O)=O)CC2)=C2OCCOC2=C1', 'CN1N=CC(Cl)=C1C1=C(Cl)SC(=C1)C(=O)N[C@H](CN)CC1=CC=CC(F)=C1', 'COC1=NN=C2C=CC(=NN12)N1CCC(CC1)C1=CC=C(OCCN2CCN(C)C(=O)[C@H]2C)C=C1', '[H][C@]1(C)CCC[C@@H]2[C@H](C[C@H](OC(=O)C[C@H](O)C(C)(C)C(=O)[C@H](C)[C@H]1O)C(\\C)=C\\C1=CSC(C)=N1)N2CCOC(=O)OCCSSC[C@H](NC(=O)[C@H](CC(O)=O)NC(=O)[C@H](CCCNC(N)=N)NC(=O)[C@H](CC(O)=O)NC(=O)CC[C@H](NC(=O)C1=CC=C(NCC2=CN=C3N=C(N)NC(=O)C3=N2)C=C1)C(O)=O)C(O)=O', 'C\\C(\\C=C\\C1=C(C)CCCC1(C)C)=C\\C=C\\C(\\C)=C\\C(O)=O', '[Cu]', '[90Y]', 'CC(C)OC1=C2C(NC3=C(Cl)C=NC4=C3OCO4)=NC=NC2=CC(OCCN2CCN(CC2)C(C)=O)=C1', 'CO[C@H]1\\C=C\\O[C@@]2(C)OC3=C(C2=O)C2=C(C(O)=C3C)C(=O)C(NC(=O)C(C)=C\\C=C\\[C@H](C)[C@H](O)[C@@H](C)[C@@H](O)[C@@H](C)[C@H](OC(C)=O)[C@@H]1C)=C1NC3(CCN(CCN4C(C)=NC=C4[N+]([O-])=O)CC3)N=C21', 'C[C@H](NC1=C2C=NN([C@@H]3O[C@H](COP(O)(=O)CP(O)(O)=O)[C@@H](O)[C@H]3O)C2=NC(Cl)=C1)C1=CC=CC=C1F', 'COCC(=O)O[C@]1(CCN(C)CCCC2=NC3=CC=CC=C3N2)CCC2=C(C=CC(F)=C2)[C@@H]1C(C)C', 'CO[C@H]1CNCC[C@H]1NC(=O)C1=CC(Cl)=C(N)C=C1OC', 'CCCC(=O)NC1=C(I)C=C(I)C(CC(CC)C(O)=O)=C1I', 'CN1N=C(C)C(\\C=N\\OCC2=CC=C(C=C2)C(=O)OC(C)(C)C)=C1OC1=CC=CC=C1', '[O-]S(=O)(=O)C1=CC=CC=C1.[O-]S(=O)(=O)C1=CC=CC=C1.COC1=CC2=C(C=C1OC)C(CC1=CC(OC)=C(OC)C=C1)[N+](C)(CCC(=O)OCCCCCOC(=O)CC[N+]1(C)CCC3=C(C=C(OC)C(OC)=C3)C1CC1=CC(OC)=C(OC)C=C1)CC2', 'II', 'FC1=CC(=CC(F)=C1)[C@@H]1CNC2(CCCC2)C(=O)N1CC(=O)NC1=CC=C2C[C@]3(CC2=C1)C(=O)NC1=C3C=CC=N1', 'COC1=C(F)C(F)=CC=C1[C@@H]1[C@H](C)[C@@](C)(O[C@H]1C(=O)NC1=CC=NC(=C1)C(N)=O)C(F)(F)F', 'CCC[C@@]1(CCC2=CC=CC=C2)CC(O)=C([14C@H](CC)C2=CC=CC(NS(=O)(=O)C3=NC=C(C=C3)C(F)(F)F)=C2)C(=O)O1', 'N[C@@H](CCC(O)=O)C(=O)N[C@@H](CC1=CNC2=C1C=CC=C2)C(O)=O', 'CC(C1=C(CCN(C)C)CC2=CC=CC=C12)C1=CC=CC=N1', 'CN(C)C(=N)NC(N)=N', 'FCOC(C(F)(F)F)C(F)(F)F', 'CC(C)NC(=O)NS(=O)(=O)C1=C(NC2=CC=CC(C)=C2)C=CN=C1', '[H][C@]12SCC(CSC3=NN=NN3C)=C(N1C(=O)[C@]2(NC(=O)C1SC(S1)=C(C(N)=O)C(O)=O)OC)C(O)=O', 'ClC1=C(CN2CCCC2=N)NC(=O)NC1=O', 'OC(=O)C1=CC=C(C=C1)C1(CC1)NC(=O)C1CC2(CC2)CCN1CC1=CC=C(C=C1)C(F)(F)F', '[Mn++].[H][C@@](O)(CO)[C@@]([H])(O)[C@]([H])(O)[C@@]([H])(O)C([O-])=O.[H][C@@](O)(CO)[C@@]([H])(O)[C@]([H])(O)[C@@]([H])(O)C([O-])=O', 'CCC\\N=C1/S\\C(=C/C2=CC=C(OC[C@H](O)CO)C(Cl)=C2)C(=O)N1C1=CC=CC=C1C', '[H][C@@]12CC[C@](O)(C(=O)CO)[C@@]1(C)CC=C1[C@@]2([H])CCC2=CC(=O)CC[C@]12C', 'CN(C)CC[C@H](CSC1=CC=CC=C1)NC1=CC=C(C=C1[N+]([O-])=O)S(=O)(=O)NC(=O)C1=CC=C(C=C1)N1CCN(CC2=CC=CC=C2C2=CC=C(Cl)C=C2)CC1', 'CN(C)C[C@@H](NC(=O)N1CC2=C(NN=C2NC2=C3SC=CC3=NC(C)=N2)C1(C)C)C1=CC=CC=C1', '[Na+].OP(=O)=O.OP(=O)=O.OP(=O)=O.OP(=O)=O.OP(=O)=O.[O-]P(=O)=O.[H][C@@]12C[C@@]3([H])C(=C(O)[C@]1(O)C(=O)C(C(N)=O)=C(O)[C@H]2N(C)C)C(=O)C1=C(O)C=CC=C1[C@@]3(C)O.[H][C@@]12C[C@@]3([H])C(=C(O)[C@]1(O)C(=O)C(C(N)=O)=C(O)[C@H]2N(C)C)C(=O)C1=C(O)C=CC=C1[C@@]3(C)O.[H][C@@]12C[C@@]3([H])C(=C(O)[C@]1(O)C(=O)C(C(N)=O)=C(O)[C@H]2N(C)C)C(=O)C1=C(O)C=CC=C1[C@@]3(C)O.[H][C@@]12C[C@@]3([H])C(=C(O)[C@]1(O)C(=O)C(C(N)=O)=C(O)[C@H]2N(C)C)C(=O)C1=C(O)C=CC=C1[C@@]3(C)O.[H][C@@]12C[C@@]3([H])C(=C(O)[C@]1(O)C(=O)C(C(N)=O)=C(O)[C@H]2N(C)C)C(=O)C1=C(O)C=CC=C1[C@@]3(C)O', 'O.O[Al](O)O.O[Al](O)OS(=O)(=O)OC[C@H]1O[C@@](COS(=O)(=O)O[Al](O)O)(O[C@H]2O[C@H](COS(=O)(=O)O[Al](O)O)[C@@H](OS(=O)(=O)O[Al](O)O)[C@H](OS(=O)(=O)O[Al](O)O)[C@H]2OS(=O)(=O)O[Al](O)O)[C@@H](OS(=O)(=O)O[Al](O)O)[C@@H]1OS(=O)(=O)O[Al](O)O', '[H][C@@]1([C@H](OC)[C@@H](CC[C@]11CO1)OC(=O)N1CC(CCN2CCOCC2)C1)[C@@]1(C)O[C@@H]1CC=C(C)C', 'CC(C)C1=C(NC2=CC=C(C=C12)C1CCN(CC(N)=O)CC1)C1=CN2N=CN=C2C(C)=C1C', 'OB(O)C1=CC=C(OC(F)(F)F)C=C1CSC1=NC=C(C=N1)C(=O)NC1=CC=C(F)C=C1', 'CC1=NC(C#CC2=CC=NC(Cl)=C2)=C(C)N1C1=CC=C(F)C=C1', 'COC1=CC(=CC=C1NC1=NC=C(C(CCC2=CC=CC=C2CC(N)=O)=N1)C(F)(F)F)C1CCN(C)CC1', 'CCOC1=C(NC(=O)\\C=C\\CN(C)C)C=C2C(NC3=CC=C(OCC4=CC=CC(F)=C4)C(Cl)=C3)=C(C=NC2=C1)C#N', 'CC(C)[C@@H]1NC(=O)[C@H](CCCCN)NC(=O)[C@@H](CC2=CNC3=CC=CC=C23)NC(=O)[C@H](CC2=CC=C(O)C(I)=C2)NC(=O)[C@H](CSSC[C@H](NC1=O)C(=O)N[C@@H]([C@@H](C)O)C(N)=O)NC(=O)[C@H](N)CC1=CC=C(N)C(I)=C1', 'CC(OC(C)=O)OC(=O)C(C)C1=CC(F)=C(C=C1)C1=CC=CC=C1', 'NC1=NC(=O)C2=C(N1)N(COCCO)C=N2', 'COC1=CC=C2CN([C@@H](CC2=C1OCC1=CC=CC=C1)C(O)=O)C(=O)C(C1=CC=CC=C1)C1=CC=CC=C1', 'CCC1=CN=C(N=C1)N1CCC(CC1)C1=NC(COC2=CC=C(C=C2)N2C=NN=N2)=CS1', 'CN1CCN(CCCN2C(C)=C(C)C3=CC(OC4=CC(=CC=C4)C(=O)N4CCN(CCC5=CC=C(F)C=C5)CC4)=CC=C23)CC1', 'COC1=CC=CC2=C1C1=C(N2)C2=C(CCC2)C2=C1C(=O)N(CN1CCN(C)CC1)C2=O', '[11CH3]NC1=CC=C(C=C1)C1=NC2=C(S1)C=C(O)C=C2', 'CCC1=NN(C2CCCC2)C2=C1CCN1C(=NN=C21)C1=CC=CS1', 'CC[C@H]1[C@@H](CC2=CN=CN2C)COC1=O', 'CC1=CC(C)=C2CN(CC2=N1)C(=O)CC1CN(C1)C1=CC=NC(=C1)C(F)(F)F', 'COC1=CC(=CC(OC)=C1OC)[C@@H](O)CC1=CC(O)=C(OC)C=C1', 'CCCCOC1=C(OC)C=C(C=C1OC)C(=O)NCC1(CCOCC1)N(C)C', 'CN(CCO)CC(O)CN1C=NC2=C1C(=O)N(C)C(=O)N2C', 'CC1=NC(C)=C(N=C1C1=CC=C(C=C1)[C@H]1CC[C@H](CC(O)=O)CC1)C(N)=O', 'CC1=C(SSC1=S)C1=CN=CC=N1', '[Na+].[Na+].[Na+].[Na+].CC1=CC(=CC=C1\\N=N\\C1=C([O-])C2=C(C=C1)C(=CC(=C2N)S(O)(=O)=O)S([O-])(=O)=O)C1=CC=C(\\N=N\\C2=C([O-])C3=C(C=C2)C(=CC(=C3N)S(O)(=O)=O)S([O-])(=O)=O)C(C)=C1', 'O=C(N1CCOCC1)C1=CC=C(C=C1)C1=CN2C(C=C1)=NC=C2C1=CC=C(C=C1)C#N', 'CCCCCCCCOC(=O)C(=C)C#N', 'CCCCCCOC1=NSN=C1C1=CCCN(C)C1', '[Gd+3].CC(O)

In [34]:
processed_smiles = []
warning_smiles = []
for smiles in db_smiles:
    try:
        mol = MolFromSmiles(smiles)
        Chem.Kekulize(mol)
        new_smile = MolToSmiles(mol, isomericSmiles=False, kekuleSmiles=True)
        processed_smiles.append(new_smile)
    except:
        warning_smiles.append(new_smile)
processed_smiles.extend(warning_smiles)

[10:57:22] Explicit valence for atom # 1 Cl, 4, is greater than permitted
[10:57:22] Explicit valence for atom # 84 N, 4, is greater than permitted
[10:57:22] Explicit valence for atom # 1 B, 6, is greater than permitted
[10:57:23] SMILES Parse Error: syntax error while parsing: OC1=CC=CC(=C1)C-1=C2\CCC(=N2)\C(=C2/N\C(\C=C2)=C(/C2=N/C(/C=C2)=C(\C2=CC=C\-1N2)C1=CC(O)=CC=C1)C1=CC(O)=CC=C1)\C1=CC(O)=CC=C1
[10:57:23] SMILES Parse Error: Failed parsing SMILES 'OC1=CC=CC(=C1)C-1=C2\CCC(=N2)\C(=C2/N\C(\C=C2)=C(/C2=N/C(/C=C2)=C(\C2=CC=C\-1N2)C1=CC(O)=CC=C1)C1=CC(O)=CC=C1)\C1=CC(O)=CC=C1' for input: 'OC1=CC=CC(=C1)C-1=C2\CCC(=N2)\C(=C2/N\C(\C=C2)=C(/C2=N/C(/C=C2)=C(\C2=CC=C\-1N2)C1=CC(O)=CC=C1)C1=CC(O)=CC=C1)\C1=CC(O)=CC=C1'
[10:57:23] WARNING: not removing hydrogen atom without neighbors
[10:57:23] WARNING: not removing hydrogen atom without neighbors
[10:57:23] Conflicting single bond directions around double bond at index 46.
[10:57:23]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:57:23] WARNING: not removing hydrogen atom without neighbors
[10:57:23] WARNING: not removing hydrogen atom without neighbors
[10:57:23] WARNING: not removing hydrogen atom without neighbors
[10:57:23] WARNING: not removing hydrogen atom without neighbors
[10:57:23] WARNING: not removing hydrogen atom without neighbors

In [35]:
len(processed_smiles)

6116

In [36]:
processed_smiles[:5]

['CN(C)CCOC1(C2=CC=CC=C2)CC2CCC1(C)C2(C)C',
 'COC1=C(OC(=O)N2CCN(C)CC2C)C=C2C(NC3=C(F)C(Cl)=CC=C3)=NC=NC2=C1',
 'FC1=C(F)C=C(CN2CCC(NC3=CC=C(C(F)(F)F)N=N3)CC2)C=C1',
 'COCCCC(NC(=O)C1CCCN1C(=O)C(CC1=CC=CC=C1)NC(=O)OCC1=CC=CC=C1)B(O)O',
 'CC1=CC(=O)N(O)C(C2CCCCC2)=C1']

In [37]:
def has_ring(smile:str):
    return any(s.isdigit() for s in smile)

In [38]:
for i in range(len(processed_smiles)):
    processed_smiles[i] = re.sub(r'Cl', 'L', processed_smiles[i])

    processed_smiles[i] = processed_smiles[i].upper()
    
    for digit in map(str, range(10)):
        if digit in processed_smiles[i]:
            processed_smiles[i] = re.sub(digit, 'X', processed_smiles[i], count=1)

    processed_smiles[i] = re.sub(r'C\(F\)\(F\)\(F\)', 'W', processed_smiles[i])

    processed_smiles[i] = re.sub(r'S\(=O\)\(=O\)', 'U', processed_smiles[i])

    processed_smiles[i] = re.sub(r'S\(=O\)(?!\(=O\))', 'M', processed_smiles[i])

In [39]:
df_smiles = pd.DataFrame(processed_smiles, columns=['SMILES'])
df_smiles.to_csv('db_app_inv_smiles.csv',index=False)

In [40]:
common_ngrams = set()
for smile in processed_smiles:
    ngram_s = set(
        smile[i:i+l]
        for l in range(0,6)
        for i in range(len(smile)-l)
    )
    common_ngrams|=ngram_s
print(len(common_ngrams))

18765

In [41]:
result = defaultdict(lambda:defaultdict(int))
for smile in processed_smiles:
    for ngram in common_ngrams:
        start = 0
        while True:
            idx = smile.find(ngram, start)
            if idx == -1:
                break
            
            if idx + len(ngram) < len(smile):
                next_char = smile[idx + len(ngram)]
                result[ngram][next_char] += 1
            start = idx +1

result_dict = {ngram: dict(next_char) for ngram, next_char in result.items()}

In [42]:
tot_count = {ngram: 0 for ngram in result_dict.keys()}
for ngram, freq_dict in result_dict.items():
    tot_count[ngram] = 0
    for next_char, count in freq_dict.items():
        tot_count[ngram] += count

In [43]:
for ngram, freq_dict in result_dict.items():
    for next_char, count in freq_dict.items():
        freq = count/tot_count[ngram]
        freq_dict[next_char] = freq
    result_dict[ngram] = freq_dict

In [44]:
with open('ngram_db_app_inv.json','w') as f:
    json.dump(result_dict, f)